// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoQCrQTxW2UbfGEudFufabKFJ0h1QezAk',
    appId: '1:247331757463:web:82a643285f64f5887cf8d2',
    messagingSenderId: '247331757463',
    projectId: 'apartment-6ed7b',
    authDomain: 'apartment-6ed7b.firebaseapp.com',
    storageBucket: 'apartment-6ed7b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-R20VxgxkQwQPQvMkAqtW82vEMyz6EKk',
    appId: '1:247331757463:android:0dca2a25e6911d8e7cf8d2',
    messagingSenderId: '247331757463',
    projectId: 'apartment-6ed7b',
    storageBucket: 'apartment-6ed7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAooP4Aub4iYCfWfPNQkUF1IhyyJ2eU3M',
    appId: '1:247331757463:ios:5dfdbb39cf7b09d47cf8d2',
    messagingSenderId: '247331757463',
    projectId: 'apartment-6ed7b',
    storageBucket: 'apartment-6ed7b.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAooP4Aub4iYCfWfPNQkUF1IhyyJ2eU3M',
    appId: '1:247331757463:ios:5dfdbb39cf7b09d47cf8d2',
    messagingSenderId: '247331757463',
    projectId: 'apartment-6ed7b',
    storageBucket: 'apartment-6ed7b.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoQCrQTxW2UbfGEudFufabKFJ0h1QezAk',
    appId: '1:247331757463:web:df7bab2877b59e3c7cf8d2',
    messagingSenderId: '247331757463',
    projectId: 'apartment-6ed7b',
    authDomain: 'apartment-6ed7b.firebaseapp.com',
    storageBucket: 'apartment-6ed7b.firebasestorage.app',
  );
}
